In [91]:
import pandas as pd
import numpy as np


class demandFile():
    def __init__(self,path):
        self.demandFile = pd.read_excel(path)
        
        supplyDemandCap = self.demandFile
        supplyCols = [col for col in supplyDemandCap if col.startswith('Supply')]
        demandCols = [col for col in supplyDemandCap if col.startswith('Demand')]

        self.supply = supplyDemandCap[supplyCols ].dropna(axis=0, how='all').fillna(0).to_numpy()
        self.P = [i for i in range(len(self.supply))]
        
        self.capacity = supplyDemandCap[~supplyDemandCap['Capacity'].isna()].dropna(axis=1)['Capacity'].fillna(0).to_numpy()
        self.W = [i for i in range(len(self.capacity))]
        self.capacity = np.concatenate((np.zeros(len(self.supply)), self.capacity))

        self.demand = supplyDemandCap[demandCols].dropna(axis=0, how='all').to_numpy()
        self.U = [i for i in range(len(self.demand))]
        self.demand = np.concatenate((np.zeros([len(self.supply) + len(self.capacity),len(self.demand[0])]), self.demand))

        

        
        
    

    def printFile(self):
        print(self.demandFile)

class fixedCost():
    def __init__(self,path):
        self.fixedCost = pd.read_excel(path)

class varCost():
    def __init__(self,path):
        self.varCost = pd.read_excel(path)
    def __repr__(self):
        return print(self.varCost)
    def __str__(self):
        return 'file'
        


In [92]:
data = demandFile('./given_data/demanddata.xlsx')
f = fixedCost('./given_data/fixedcosts.xlsx')
c = varCost('./given_data/variablecosts.xlsx')

In [93]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
data.demand

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 30.,   0., 100.,   0.,   5.,  20.],
       [ 20.,  10.,   0.,  50.,  15.,  20.],
       [  0.,  10.,   0.,  50.,  10.,  20.],
       [ 10.,  10.,   0.,   0.,  25.,  20.],
       [ 40.,  20.,   0.,   0.,  40.,  20.]])

In [97]:
data.capacity

array([  0.,   0.,   0., 400., 300., 200., 300., 200.])

In [98]:
data.supply

array([[100., 100.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100., 100., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.]])

In [104]:
K = [i for i in range(len(data.demand))]
K

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]