In [91]:
import pandas as pd
import numpy as np


class demandFile():
    def __init__(self,path):
        self.demandFile = pd.read_excel(path)
        
        supplyDemandCap = self.demandFile
        supplyCols = [col for col in supplyDemandCap if col.startswith('Supply')]
        demandCols = [col for col in supplyDemandCap if col.startswith('Demand')]

        self.supply = supplyDemandCap[supplyCols ].dropna(axis=0, how='all').fillna(0).to_numpy()
        self.P = [i for i in range(len(self.supply))]
        
        self.capacity = supplyDemandCap[~supplyDemandCap['Capacity'].isna()].dropna(axis=1)['Capacity'].fillna(0).to_numpy()
        self.W = [i for i in range(len(self.capacity))]
        self.capacity = np.concatenate((np.zeros(len(self.supply)), self.capacity))

        self.demand = supplyDemandCap[demandCols].dropna(axis=0, how='all').to_numpy()
        self.U = [i for i in range(len(self.demand))]
        self.demand = np.concatenate((np.zeros([len(self.supply) + len(self.capacity),len(self.demand[0])]), self.demand))

        

        
        
    

    def printFile(self):
        print(self.demandFile)

class fixedCost():
    def __init__(self,path):
        self.fixedCost = pd.read_excel(path)

class varCost():
    def __init__(self,path):
        self.varCost = pd.read_excel(path)
    def __repr__(self):
        return print(self.varCost)
    def __str__(self):
        return 'file'
        


In [92]:
data = demandFile('./given_data/demanddata.xlsx')
f = fixedCost('./given_data/fixedcosts.xlsx')
c = varCost('./given_data/variablecosts.xlsx')

In [93]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
data.demand

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 30.,   0., 100.,   0.,   5.,  20.],
       [ 20.,  10.,   0.,  50.,  15.,  20.],
       [  0.,  10.,   0.,  50.,  10.,  20.],
       [ 10.,  10.,   0.,   0.,  25.,  20.],
       [ 40.,  20.,   0.,   0.,  40.,  20.]])

In [97]:
data.capacity

array([  0.,   0.,   0., 400., 300., 200., 300., 200.])

In [98]:
data.supply

array([[100., 100.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100., 100., 100.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.]])

In [104]:
K = [i for i in range(len(data.demand))]
K

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [74]:
import itertools
import numpy as np
#print(list(itertools.permutations('56789', 5)))

permutations = [''.join(sub) for sub in itertools.permutations('56789', 5)]  # all permutations of universities

ordered_total_costs = dict.fromkeys(permutations, np.zeros(5))

allP = [] 
for p in ordered_total_costs:
    steps = [p[:i] for i in range(1, len(p) + 1)]
    
    # print(steps)
    # for s in steps:
    #     steps_int = [int(u) for u in np.array(s)]
    #     print(steps_int)
    #     for universities_in_tour in steps_int:
    #         print(universities_in_tour)

    allSubsections = []
    for s in steps:
        subList = []
        for i in range(len(s)):
            subList.append(int(s[i]))
        allSubsections.append(subList)
    allP.append(allSubsections)


[5]


In [91]:
demandData.demand

array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [ 30.,   0., 100.,   0.,   5.,  20.],
       [ 20.,  10.,   0.,  50.,  15.,  20.],
       [  0.,  10.,   0.,  50.,  10.,  20.],
       [ 10.,  10.,   0.,   0.,  25.,  20.],
       [ 40.,  20.,   0.,   0.,  40.,  20.]])

In [93]:
np.zeros_like(demandData.demand)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [97]:
half = np.ones_like(demandData.demand)*0.5

In [98]:
tens = np.array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [10., 10., 10., 10., 10., 10.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [99]:
tens * half

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [103]:
demandData.W[2:]

[5, 6, 7]

In [123]:
varCost = pd.read_excel('./given_data/variablecosts.xlsx').iloc[:,1:].to_numpy()

In [125]:
fixedCost = pd.read_excel('./given_data/fixedcosts.xlsx').to_numpy()


In [126]:
fixedCost

array([['P1', 12.5, 19.63008577301995, 20.586027923844426,
        14.4812827494399, 24.12524615696096, 15.03713661132247,
        19.830266518182388, 14.355268240455386, 25.692515671359217,
        21.591933296470955, 17.50252855970261, 21.586991007514534,
        20.657149137020514],
       ['P2', 19.63008577301995, 12.5, 15.86420295379256,
        20.68188207229072, 17.362218431873757, 20.637692807175586,
        14.788181277265661, 18.289323938457287, 18.56446684742604,
        18.611956717974937, 16.557731048950487, 17.503247772988324,
        17.756442237342355],
       ['P3', 20.586027923844426, 15.86420295379256, 12.5,
        20.859080543744327, 16.650804629012406, 20.534213238575994,
        18.152370599365515, 18.799565895181356, 19.340103715472036,
        15.31098296891217, 19.40823142454645, 14.142714846067813,
        21.111872824262896],
       ['W1', 14.4812827494399, 20.68188207229072, 20.859080543744327,
        12.5, 24.751585764964233, 13.207884367462533, 21.315763